// ignore_for_file: constant_identifier_names

class ATImgStrings{
  const ATImgStrings._();

  static const String _svgPath = 'assets/images/svg_images';
  static const String _generalJpegImagePath = 'assets/images/jpeg_images';
  static const String _pngPath = 'assets/images/png_images';

  static const String emptyImage = '$_svgPath/empty_image.svg';
  static const String amptiveLogo = '$_svgPath/Logo.svg';
  static const String logo2 = '$_svgPath/amptive_logotype.svg';
  static const String WALLET_ICON = '$_svgPath/WALLET ICON.svg';
  static const String SHOW_ICON = '$_svgPath/Frame 79.svg';
  static const String WIFI_ICON = '$_svgPath/Start or Schedule.svg';
  static const String robot = '$_svgPath/delivery robot.svg';
  static const String filledBell = '$_svgPath/Bell=Fill.svg';
  static const String outlinedBell = '$_svgPath/Bell=Outline.svg';
  static const String filledSearch = '$_svgPath/Discover animation icon=Fill.svg';
  static const String outlinedSearch = '$_svgPath/Discover animation icon=Outline.svg';
  static const String filledHome = '$_svgPath/Home=Fill.svg';
  static const String outlinedHome = '$_svgPath/Home button.svg';
  static const String filledBroadCast = '$_svgPath/Broadcast icon=Fill.svg';
  static const String outlinedBroadCast = '$_svgPath/Broadcast icon=Outline.svg';
  static const String CALEND_ICON = '$_svgPath/Contextual menu icon.svg';
  static const String PERSON_CHECKED = '$_svgPath/Contextual menu icon (1).svg';
  static const String SHARE_LIVE = '$_svgPath/Icon.svg';
  static const String FOLLOW_ICON = '$_svgPath/Icon (1).svg';
  static const String UNFOLLOW_ICON = '$_svgPath/Icon (2).svg';
  static const String GIFT_ICON = '$_svgPath/gift.svg';
  static const String MICROPHONE = '$_svgPath/Microphone.svg';
  static const String USER_FOLLOW = '$_svgPath/user-check.svg';
  static const String KICK_USER_OUT = '$_svgPath/user out.svg';
  static const String USER_ICON = '$_svgPath/user.svg';
  static const String X_LOGO = '$_svgPath/x_logo.svg.svg';
  static const String GROUP_ICON = '$_svgPath/Group_fill.svg';
  static const String TOP_CREATOR_BADGE = '$_svgPath/RANK BADGES.svg';
  static const String SUBSCRIBER_BADGE = '$_svgPath/Subscribers badge.svg';
  static const String BIZ_ACCT_LOGO = '$_svgPath/Simplification (3).svg';
  static const String CREATOR_ACCT_LOGO = '$_svgPath/Simplification.svg';
  static const String FLUTTERWAVE = '$_svgPath/flutter_wave.svg';
  static const String APPLE_ICON = '$_svgPath/apple_icon.svg';
  static const String PAYPAL_ICON = '$_svgPath/paypal.svg';
  static const String NAIRA_ICON = '$_svgPath/₦.svg';
  static const String HASH_ICON = '$_svgPath/hash.svg';
  // static const String CREATOR_MIC = '$_svgPath/creator-microphone.svg';
  // static const String CREATOR_GIF = '$_svgPath/creatorgif.svg';
  // static const String CREATOR_GLOBE = '$_svgPath/internet.svg';
  // static const String CREATOR_LOCK = '$_svgPath/lock with heart.svg';

  static const String jpeg2 = '$_generalJpegImagePath/welcomeAvatar2.jpeg';
  static const String jpeg1 = '$_generalJpegImagePath/welcomeAvatar1.jpeg';
  static const String jpeg3 = '$_generalJpegImagePath/welcomeAvatar3.jpeg';
  static const String weCanDoHardThingsBgImage = '$_generalJpegImagePath/weCanDoAllThings.jpg';

  static const String facebookIcon = '$_pngPath/facebook.png';
  static const String GOOGLE_ICON = '$_pngPath/google_icon.png';
  static const String noAvatarImage = '$_pngPath/no_avatar_image.png';
  static const String discoverPic1 = '$_pngPath/Frame 156.png';
  static const String OFFICE_LADIES = '$_pngPath/Frame 22.png';
  static const String endlessThread = '$_pngPath/Frame 71.png';
  static const String GROUP_ICON_BLUE = '$_pngPath/Group_fill.png';
  static const String JOE_POMP_SHOW = '$_pngPath/Frame 71 (1).png';
  static const String CRIMINAL = '$_pngPath/Frame 71 (2).png';
  static const String COMMUNITY_CARD = '$_pngPath/Community card 1.png';
  static const String MAN_PHOTO = '$_pngPath/Pexels Photo by Key  Notez.png';
  static const String CREATE_EVENT_ICON = '$_pngPath/cube tiny (1).png';
  static const String event2 = '$_pngPath/cube tiny.png';
  static const String CREATE_SHOW_ICON = '$_pngPath/Group 31 (1).png';
  static const String event4 = '$_pngPath/Group 31.png';
  static const String PADLOCK = '$_pngPath/metalic padlock.png';
  static const String PEOPLE = '$_pngPath/people.png';
  static const String createShowPlaceholderImage = '$_pngPath/create-show-placeholder.png';
  static const String artCard = '$_pngPath/art-card.png';
  static const String techCard= '$_pngPath/tech-card.png';
  static const String societyCard = '$_pngPath/society-card.png';
  static const String MIC_ICON = '$_pngPath/public speaking.png';
  static const String MONEY_ICON = '$_pngPath/Stack of bills.png';
  static const String CREATOR_MIC = '$_pngPath/microphone.png';
  static const String CREATOR_GIF = '$_pngPath/gift.png';
  static const String CREATOR_GLOBE = '$_pngPath/internet.png';
  static const String CREATOR_LOCK = '$_pngPath/lock with heart.png';
  static const String INFO_ICON = '$_pngPath/price tag.png';
  static const String BIZ_ARROW = '$_pngPath/arrow decor.png';
  static const String BIZ_TICKETS = '$_pngPath/interface design window.png';
  static const String BIZ_THUNDER = '$_pngPath/lightning.png';
  static const String BIG_WALLET_ICON = '$_pngPath/wallet.png';
  static const String BIG_WALLET_COLORED_ICON = '$_pngPath/wallet (1).png';
  static const String WARNING_ICON = '$_pngPath/warning.png';
  static const String WIRE_TRANSFER = '$_pngPath/wiretransfer.png';
  static const String PAPER_PLANE = '$_pngPath/paper plane.png';
}